services:
  sqlserver:
    container_name: RR_mssql
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "MyPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:




  dotnet ef migrations add InitialCreate --startup-project ../API

dotnet ef database update --startup-project ../API